#! /bin/bin/awk -f

# lcunfold3 - unfold lines folded with <allOneLine>...</allOneLine>
# Copyright (C) 2019  Erik Auerswald <auerswal@unix-ag.uni-kl.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Unfold (re-combine) lines folded as described in section 2.1 of RFC 4475.
# A sequence of lines enclosed in the tags <allOneLine> and </allOneLine>
# (no content in a line containing a tag, no nested tags) are recombined
# into a single line.

/<allOneLine>/ {
  state = 1
  next
} 
/<\/allOneLine>/ {
  print buf
  state = 0
  buf = ""
  next
} 
{
  if (state == 1) {
    buf = buf $0
  } else {
    print
  }
}
